# Generated by Django 5.1.3 on 2024-11-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_alter_table_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
