# Generated by Django 5.1.3 on 2024-11-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0007_alter_table_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
